.586
.MODEL FLAT, STDCALL
includelib kernel32.lib
ExitProcess PROTO : DWORD
MessageBoxA PROTO : DWORD, : DWORD, : DWORD, : DWORD
.STACK 4096
.CONST
.DATA
OK EQU 0
TEXT_MESSAGE DB "SE_Asm04", 0
HW DD ?
CHARSTR DB "char: a", 0
CHARLITERALSTR DB "charliteral: v", 0
.CODE
main PROC
INVOKE MessageBoxA, 0, OFFSET CHARSTR, OFFSET TEXT_MESSAGE, OK
INVOKE MessageBoxA, 0, OFFSET CHARLITERALSTR, OFFSET TEXT_MESSAGE, OK
push 0
call ExitProcess
main ENDP
END main
